### ISSUE TITLE
Error during installation - Raspbian Lite

### ISSUE THREAD

**Issue by FedericoFedeFede** [t1m0thyj/AssistantPi#16]
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
git is already the newest version (1:2.11.0-3+deb9u4).
python3-dev is already the newest version (3.5.3-1).
python3-numpy is already the newest version (1:1.12.1-3).
virtualenv is already the newest version (15.1.0+ds-1).
libttspico-utils is already the newest version (1.0+git20130326-5).
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
Cloning into '/root/AIY-projects-python'...
remote: Enumerating objects: 468, done.
remote: Counting objects: 100% (468/468), done.
remote: Compressing objects: 100% (379/379), done.
remote: Total 2629 (delta 158), reused 335 (delta 85), pack-reused 2161
Ricezione degli oggetti: 100% (2629/2629), 1.36 MiB | 1.80 MiB/s, done.
Risoluzione dei delta: 100% (1399/1399), done.
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /root/AIY-projects-python/env/bin/python3
Also creating executable in /root/AIY-projects-python/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining file:///root/AIY-projects-python/src
Collecting google-assistant-library==1.0.1 (from aiy-projects-python==1.2)
  Could not find a version that satisfies the requirement google-assistant-library==1.0.1 (from aiy-projects-python==1.2) (from versions: 0.0.2, 0.0.3, 0.1.0, 0.1.1, 1.0.0)
No matching distribution found for google-assistant-library==1.0.1 (from aiy-projects-python==1.2)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting google-auth-oauthlib
  Using cached https://files.pythonhosted.org/packages/46/df/d1f94ee2cffe5a83721f262efe51f3b2dcdd3b616caf007b8490e824c550/google_auth_oauthlib-0.2.0-py2.py3-none-any.whl
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/lib/python3/dist-packages (from google-auth-oauthlib) (0.7.0)
Collecting google-auth (from google-auth-oauthlib)
  Using cached https://files.pythonhosted.org/packages/24/62/8b9612b1055cfbecd577e252446fe5f939f6818d0b7ddc27bb872f233cd4/google_auth-1.6.1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from google-auth->google-auth-oauthlib) (1.10.0)
Collecting rsa>=3.1.4 (from google-auth->google-auth-oauthlib)
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth->google-auth-oauthlib)
  Using cached https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth->google-auth-oauthlib)
  Using cached https://files.pythonhosted.org/packages/76/7e/08cd3846bebeabb6b1cfc4af8aae649d90249b4aeed080bddb5297f1d73b/cachetools-3.0.0-py2.py3-none-any.whl
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa>=3.1.4->google-auth->google-auth-oauthlib) (0.1.9)
pyasn1-modules 0.2.2 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.1.9 which is incompatible.
Installing collected packages: rsa, pyasn1-modules, cachetools, google-auth, google-auth-oauthlib
Successfully installed cachetools-3.0.0 google-auth-1.6.1 google-auth-oauthlib-0.2.0 pyasn1-modules-0.2.2 rsa-4.0
Created symlink /etc/systemd/system/multi-user.target.wants/AssistantPi.service → /lib/systemd/system/AssistantPi.service.
Traceback (most recent call last):
  File "src/AssistantPi.py", line 7, in <module>
    import examples.voice.assistant_library_with_local_commands_demo as assistant
  File "/root/AIY-projects-python/src/examples/voice/assistant_library_with_local_commands_demo.py", line 29, in <module>
    from google.assistant.library.event import EventType
ImportError: No module named 'google.assistant'

**Comment by SlainV** [comment]
Same, but on desktop version.
