### ISSUE TITLE
error register() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by mathieusayag** [t1m0thyj/AssistantPi#20]
Created symlink /etc/systemd/system/multi-user.target.wants/AssistantPi.service → /lib/systemd/system/AssistantPi.service.
Traceback (most recent call last):
  File "src/AssistantPi.py", line 8, in <module>
    assistant.main()
  File "/home/pi/AIY-projects-python/src/examples/voice/assistant_library_with_local_commands_demo.py", line 83, in main
    credentials = auth_helpers.get_assistant_credentials()
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 132, in get_assistant_credentials
    return _try_to_get_credentials(credentials_file)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 123, in _try_to_get_credentials
    credentials = _credentials_flow_interactive(client_secrets)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 75, in _credentials_flow_interactive
    webbrowser.register('chromium-browser', None, webbrowser.Chrome('chromium-browser'), -1)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given

**Comment by Avi-avidan** [comment]
Experiencing same issue with RPI4B+ and aiy voice HAT (voice kit v1.0)

**Comment by robbie-vonken** [comment]
Also Experiencing same issue with RPI4B+ and aiy voice HAT (voice kit v1.0)

pi@robbie:~/AIY-projects-python $ src/examples/voice/assistant_library_demo.py
Traceback (most recent call last):
  File "src/examples/voice/assistant_library_demo.py", line 71, in <module>
    main()
  File "src/examples/voice/assistant_library_demo.py", line 64, in main
    credentials = auth_helpers.get_assistant_credentials()
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 151, in get_assistant_credentials
    return _try_to_get_credentials(credentials_file)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 123, in _try_to_get_credentials
    credentials = _credentials_flow_interactive(client_secrets)
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 75, in _credentials_flow_interactive
    webbrowser.register('chromium-browser', None, webbrowser.Chrome('chromium-browser'), -1)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given



image AIY Kits Release 2019-11-13

https://aiyprojects.withgoogle.com/voice/#google-assistant--run-the-assistant-demo
says:
Type the following command line and press enter:
voice/assistant_grpc_demo.py (incorrect the path is incomplete)
src/examples/voice/assistant_library_demo.py (correct)

**Comment by zxcj04** [comment]
provide a temporary solution:

make a backup of auth_helpers.py

modify the 75 line to "webbrowser.register('chromium-browser', None, webbrowser.Chrome('chromium-browser'))"

restart assistant_library_demo.py , it may work~

**Comment by robbie-vonken** [comment]
Thank you for this feedback
I have modified the file line 75 in:
/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py
and then could execute
src/examples/voice/assistant_grpc_demo.py
carry out authentication
all perfect
