### ISSUE TITLE
Failed Installation

### ISSUE THREAD

**Issue by andiwest** [t1m0thyj/AssistantPi#4]
I'm using a Raspberry Pi Model B running a fresh install of Raspbian Lite, and got these errors in red when installing.

Near the beginning
`Failed building wheel for grpcio`
`google-api-core 0.1.4 has requirement requests<3.0.0dev,>=2.18.0, but you'll have requests 2.14.2 which is incompatible.`
Later
`Command "/home/pi/AIY-projects-python/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-sahr233f/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ucid12_k/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/AIY-projects-python/env/include/site/python3.5/grpcio" failed with error code 1 in /tmp/pip-install-sahr233f/grpcio/`
I've attached the full log.

I attempted you test to see if it works,
`source env/bin/activate && env/bin/python3 -u src/AssistantPi.py`
And got the responce,
`Traceback (most recent call last):
  File "src/AssistantPi.py", line 29, in <module>
    import aiy.assistant.auth_helpers
ImportError: No module named 'aiy'`

[Install-Unsuccessful.log](https://github.com/t1m0thyj/AssistantPi/files/2342429/Install-Unsuccessful.log)

**Comment by Gfermoto** [comment]
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Уже установлен пакет git самой новой версии (1:2.11.0-3+deb9u4).
Уже установлен пакет python3-dev самой новой версии (3.5.3-1).
python3-dev установлен вручную.
Уже установлен пакет python3-numpy самой новой версии (1:1.12.1-3).
Уже установлен пакет libttspico-utils самой новой версии (1.0+git20130326-5).
Будут установлены следующие дополнительные пакеты:
  python3-virtualenv
НОВЫЕ пакеты, которые будут установлены:
  python3-virtualenv virtualenv
обновлено 0, установлено 2 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
Необходимо скачать 77,4 kБ архивов.
После данной операции, объём занятого дискового пространства возрастёт на 171 kB.
Хотите продолжить? [Д/н] y
Пол:1 http://mirror.yandex.ru/mirrors/raspbian/raspbian stretch/main armhf python3-virtualenv all 15.1.0+ds-1 [57,7 kB]
Пол:2 http://mirror.yandex.ru/mirrors/raspbian/raspbian stretch/main armhf virtualenv all 15.1.0+ds-1 [19,7 kB]
Получено 77,4 kБ за 0с (88,8 kБ/c)
Выбор ранее не выбранного пакета python3-virtualenv.
(Чтение базы данных … на данный момент установлено 130875 файлов и каталогов.)
Подготовка к распаковке …/python3-virtualenv_15.1.0+ds-1_all.deb …
Распаковывается python3-virtualenv (15.1.0+ds-1) …
Выбор ранее не выбранного пакета virtualenv.
Подготовка к распаковке …/virtualenv_15.1.0+ds-1_all.deb …
Распаковывается virtualenv (15.1.0+ds-1) …
Настраивается пакет python3-virtualenv (15.1.0+ds-1) …
Обрабатываются триггеры для man-db (2.7.6.1-2) …
Настраивается пакет virtualenv (15.1.0+ds-1) …
fatal: целевой путь «/home/pi/AIY-projects-python» уже существует и не является пустым каталогом.
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /opt/aiy/projects-python/env/bin/python3
Also creating executable in /opt/aiy/projects-python/env/bin/python
Failed to import the site module
Traceback (most recent call last):
  File "/opt/aiy/projects-python/env/lib/python3.5/site.py", line 703, in <module>
    main()
  File "/opt/aiy/projects-python/env/lib/python3.5/site.py", line 686, in main
    paths_in_sys = virtual_addsitepackages(paths_in_sys)
  File "/opt/aiy/projects-python/env/lib/python3.5/site.py", line 644, in virtual_addsitepackages
    return addsitepackages(known_paths, sys_prefix=sys.real_prefix)
  File "/opt/aiy/projects-python/env/lib/python3.5/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/opt/aiy/projects-python/env/lib/python3.5/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/opt/aiy/projects-python/env/lib/python3.5/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
AttributeError: module 'site' has no attribute 'getsitepackages'
ERROR: The executable /opt/aiy/projects-python/env/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/opt/aiy/projects-python' (should be '/opt/aiy/projects-python/env')
ERROR: virtualenv is not compatible with this system or executable
install.sh: строка 56: env/bin/pip: Нет такого файла или каталога
install.sh: строка 57: env/bin/pip: Нет такого файла или каталога
Created symlink /etc/systemd/system/multi-user.target.wants/AssistantPi.service → /lib/systemd/system/AssistantPi.service.
Traceback (most recent call last):
  File "src/AssistantPi.py", line 4, in <module>
    with open(activate_this) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'src/../env/bin/activate_this.py'

**Comment by BorGreiner** [comment]
Trying to install Assistant on Jessie. Using RPi for audio only, so I do not have any UI. 

Could not find any downloads that satisfy the requirement google-assistant-library==1.0.1 (from aiy-projects-python==1.2)
Cleaning up...
No distributions at all found for google-assistant-library==1.0.1 (from aiy-projects-python==1.2)
Storing debug log for failure in /home/pi/.pip/pip.log
Downloading/unpacking google-auth-oauthlib
  Downloading google_auth_oauthlib-0.2.0-py2.py3-none-any.whl
Downloading/unpacking requests-oauthlib>=0.7.0 (from google-auth-oauthlib)
  Downloading requests_oauthlib-1.0.0-py2.py3-none-any.whl
Downloading/unpacking google-auth (from google-auth-oauthlib)
^CCleaning up...
Operation cancelled by user

Also... how would I be able to get permissons without browser on RPi?
Can you help me out? :)
