### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by elijah067** [t1m0thyj/AssistantPi#6]
I installed the google assistant using the "bash install.sh" command. After installing i tried to reboot my device using the reboot command and nothing happens.  I checked and run the AssistantPi.py file to check if something was wrong and run the program and got this error:

Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/src/AssistantPi.py", line 29, in <module>
    import aiy.assistant.auth_helpers
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 25, in <module>
    import google_auth_oauthlib.flow
ImportError: No module named 'google_auth_oauthlib'

The google responds to simple queries such as "1+1" or "What is the weather today?" but on using custom commands such as reboot, nothing happens.

**Comment by t1m0thyj** [comment]
This seems like a duplicate of #1 and should be fixed by the workaround in my latest commit. Can you try running `git pull` and see if you have the latest version of the repo downloaded? If it pulls down changes, run `bash uninstall.sh` to clean up the broken installation and then `bash install.sh` to try reinstalling.

If it still doesn't work after doing that, could you try navigating to the `~/AIY-projects-python` folder in a terminal window and run the following command:
`env/bin/pip install google-auth-oauthlib`
and afterwards run `source env/bin/activate && env/bin/python3 -u src/AssistantPi.py` to test if Assistant is working.

**Comment by Elijah067** [comment]
So i tried to do a fresh install of the program and this happened:

I tried to reboot the pi thru voice command:

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=403913349600-thks51ije8pdbbdm6q7g9aocmr9k2233.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&state=4T7I1VwuP0CVxK4WBp5v5arxxPdRCq&access_type=offline
[2018-09-08 15:35:18,926] INFO:google_auth_oauthlib.flow:"GET /?state=4T7I1VwuP0CVxK4WBp5v5arxxPdRCq&code=4/VABKKYHJntL8eaVneBKUC24ENoPWOuooBr4n3gFpzuPzvKrRjLgqF02Shf5NG0sicZOR5yfgzNuk2bwqUYZwt4U HTTP/1.1" 200 65
[2018-09-08 15:35:19,256] INFO:root:OAuth credentials initialized: /home/pi/.cache/voice-recognizer/assistant_credentials.json
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED
Say "OK, Google" then speak, or press Ctrl+C to quit...
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {'text': 'reboot'}
You said: reboot
/bin/sh: 1: pico2wave: not found
aplay: playback:2787: read error
Traceback (most recent call last):
  File "src/AssistantPi.py", line 104, in <module>
    main()
  File "src/AssistantPi.py", line 100, in main
    process_event(assistant, event)
  File "src/AssistantPi.py", line 75, in process_event
    reboot_pi()
  File "src/AssistantPi.py", line 47, in reboot_pi
    aiy.audio.say('See you in a bit!')
  File "/home/pi/AIY-projects-python/src/aiy/audio.py", line 133, in say
    tts.say(words, lang=lang, volume=volume, pitch=pitch)
  File "/home/pi/AIY-projects-python/src/aiy/voice/tts.py", line 37, in say
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pico2wave --wave /tmp/5524a3aa8e3e4be491fc0a26eea40bc2.wav --lang en-US "<volume level='60'><pitch level='130'><speed level='100'>See you in a bit!</speed></pitch></volume>" | aplay -D default -' returned non-zero exit status 1
install.sh: line 49:  3207 Segmentation fault      env/bin/python3 src/AssistantPi.py

I tried to do the second option and this happened:

[3618:3640:ERROR:audio_input_processor.cc(748)] Input error
ON_MUTED_CHANGED:
  {'is_muted': False}
/home/pi/AIY-projects-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(channel, GPIO.OUT)
ON_START_FINISHED
Say "OK, Google" then speak, or press Ctrl+C to quit...
[3618:3644:ERROR:audio_input_processor.cc(748)] Input error

**Comment by Elijah067** [comment]
I rechecked the AssistantPi.py script and the problem showed the same problem:

Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/src/AssistantPi.py", line 29, in <module>
    import aiy.assistant.auth_helpers
  File "/home/pi/AIY-projects-python/src/aiy/assistant/auth_helpers.py", line 25, in <module>
    import google_auth_oauthlib.flow
ImportError: No module named 'google_auth_oauthlib'

I am using a raspberry model B+ if that helps.
