### ISSUE TITLE
No Module Named aiy

### ISSUE THREAD

**Issue by wilims89** [t1m0thyj/AssistantPi#8]
Hi,

I Installed using the first choice (bash install.sh) in a raspberry pi B+

I also tried installing and uninstalling it multiple times. 

Tried `env/bin/pip install google-auth-oauthlib`
and the requirement in already satisfied then ran test
this is the result:
`source env/bin/activate && env/bin/python3 -u src/AssistantPi.py
Traceback (most recent call last):
  File "src/AssistantPi.py", line 29, in <module>
    import aiy.assistant.auth_helpers
ImportError: No module named 'aiy'
`

Pasting whole installation script below:
`bash install.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version.
virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
Cloning into '/home/pi/AIY-projects-python'...
remote: Counting objects: 2160, done.
remote: Compressing objects: 100% (434/434), done.
remote: Total 2160 (delta 260), reused 604 (delta 224), pack-reused 1494
Receiving objects: 100% (2160/2160), 1.04 MiB | 535.00 KiB/s, done.
Resolving deltas: 100% (1151/1151), done.
Checking connectivity... done.
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in env/bin/python3
Also creating executable in env/bin/python
Installing setuptools, pip...done.
Obtaining file:///home/pi/AIY-projects-python/src
  Running setup.py (path:/home/pi/AIY-projects-python/src/setup.py) egg_info for package from file:///home/pi/AIY-projects-python/src
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    
Downloading/unpacking google-assistant-grpc==0.1.0 (from aiy-projects-python==1.1)
  Downloading google_assistant_grpc-0.1.0-py2.py3-none-any.whl
Downloading/unpacking google-assistant-library==0.1.0 (from aiy-projects-python==1.1)
  Could not find any downloads that satisfy the requirement google-assistant-library==0.1.0 (from aiy-projects-python==1.1)
Cleaning up...
No distributions at all found for google-assistant-library==0.1.0 (from aiy-projects-python==1.1)
Storing debug log for failure in /home/pi/.pip/pip.log
Downloading/unpacking google-auth-oauthlib
  Downloading google_auth_oauthlib-0.2.0-py2.py3-none-any.whl
Downloading/unpacking requests-oauthlib>=0.7.0 (from google-auth-oauthlib)
  Downloading requests_oauthlib-1.0.0-py2.py3-none-any.whl
Downloading/unpacking google-auth (from google-auth-oauthlib)
  Downloading google_auth-1.5.1-py2.py3-none-any.whl (65kB): 65kB downloaded
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib)
Downloading/unpacking oauthlib>=0.6.2 (from requests-oauthlib>=0.7.0->google-auth-oauthlib)
  Downloading oauthlib-2.1.0-py2.py3-none-any.whl (121kB): 121kB downloaded
Downloading/unpacking six>=1.9.0 (from google-auth->google-auth-oauthlib)
  Downloading six-1.11.0-py2.py3-none-any.whl
Downloading/unpacking pyasn1-modules>=0.2.1 (from google-auth->google-auth-oauthlib)
  Downloading pyasn1_modules-0.2.2-py2.py3-none-any.whl (62kB): 62kB downloaded
Downloading/unpacking cachetools>=2.0.0 (from google-auth->google-auth-oauthlib)
  Downloading cachetools-2.1.0-py2.py3-none-any.whl
Downloading/unpacking rsa>=3.1.4 (from google-auth->google-auth-oauthlib)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB): 46kB downloaded
Downloading/unpacking pyasn1>=0.4.1,<0.5.0 (from pyasn1-modules>=0.2.1->google-auth->google-auth-oauthlib)
  Downloading pyasn1-0.4.4-py2.py3-none-any.whl (72kB): 72kB downloaded
Installing collected packages: google-auth-oauthlib, requests-oauthlib, google-auth, oauthlib, six, pyasn1-modules, cachetools, rsa, pyasn1
  Found existing installation: six 1.8.0
    Not uninstalling six at /usr/lib/python3/dist-packages, outside environment /home/pi/AIY-projects-python/env
Successfully installed google-auth-oauthlib requests-oauthlib google-auth oauthlib six pyasn1-modules cachetools rsa pyasn1
Cleaning up...
Created symlink from /etc/systemd/system/multi-user.target.wants/AssistantPi.service to /lib/systemd/system/AssistantPi.service.
Traceback (most recent call last):
  File "src/AssistantPi.py", line 29, in <module>
    import aiy.assistant.auth_helpers
ImportError: No module named 'aiy'`

**Comment by t1m0thyj** [comment]
By "Raspberry Pi B+", do you mean the first generation Pi, not the Pi 3? If so, the official Assistant package only works on Pi 2's and 3's which have an ARM7 CPU. If your Pi is older, I'd suggest trying [this repository](https://github.com/warchildmd/google-assistant-hotword-raspi) instead. I should add a warning to the README that this repository won't work for older Pis.

**Comment by Marcreed48** [comment]
Hi, I also installed the first option, had a “no module named aiy” also. Then I uninstalled it and tried option two, same thing. I’m using my raspberrypi3 and completed all requirements with google developer site. 
Please help a yearling noob.
Thank you.

**Comment by OJ7** [comment]
Ran into the same issue and the answer here worked for me:
https://github.com/google/aiyprojects-raspbian/issues/238#issuecomment-355436277
